THIS FILE IS FOR GENERAL RULES AND TRICKS I AM LEARNING OF PYTORCH.

In [2]:
import torch

In [3]:
tensor  = torch.tensor([1,2,3,4,5])

In [4]:
tensor.shape

torch.Size([5])

In [5]:
tensor.ndim

1

In [6]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

In [7]:
matrix.shape

torch.Size([3, 3])

In [9]:
#TIP: The number of square brackets are the number of dimensions
matrix.ndim

2

In [10]:
torch.matmul(matrix, matrix)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [11]:
torch.mul(matrix, matrix)

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [13]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [14]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 1.0
Maximum: 6.0
Mean: 3.5
Sum: 21.0


In [26]:
x = torch.tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])


x.shape

torch.Size([1, 1, 3, 3])

In [31]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0][0]}")

First square bracket:
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Second square bracket: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Third square bracket: 1
